### ISSUE TITLE
Roles and permissions

### ISSUE THREAD

**Issue by tonglil** [machuga/authority#26]
Are there any plans to make attaching roles to permissions dynamically?

I mean to create roles and then attach or remove permissions from them.

Right now the rules have to be written into the config, but I think a more dynamic system would be much more flexible.

**Comment by machuga** [comment]
@tonglil sorry - I had email alerts turned off and hadn't checked in.  A dynamic system isn't currently possible as-is, as it would require the user to keep a dictionary of what rules have been assigned, then pass the rule back to authority when removal is desired.  You are free to add rules whenever you'd like.  The config I think you're referring to is only for authority-l4 and doesn't even need to be used as-is.  Rules can still be added whenever.
