### ISSUE TITLE
Integrating Authority With Cygnite PHP Framework

### ISSUE THREAD

**Issue by jhonbendar** [machuga/authority#28]
Hi,
Authority seems cool. Interested to see if how we can Integrate with [Cygnite PHP Framework](http://www.cygniteframework.com) ?

How well we can integrate using Cygnite [Service Providers](http://www.cygniteframework.com/2015/03/service-providers.html) or [IoC container](http://www.cygniteframework.com/2013/11/ioc-container.html) or we can submit request for making Authority as core component ?

Thanks

**Comment by machuga** [comment]
Hey @jhonbendar.  I've had my email alerts disabled for a long time so I didn't see this message come in.  Integration should be pretty simple.  Just register an instance into your IoC and use that as your application's single instance of Authority and you should be ready to go.  Just have users load their rules from a model or provider or something similar.

Thanks for the interest!
